### PR TITLE
Feature deal model and view

### PR DESCRIPTION
**Pull request by andela-osule**
This build adds the following features:
+ the ability for a user to view a single deal by navigating to /deal/deal-slug
+ the ability for a user to view deal listings in each category by navigating to /deals/listings?category=category-slug

### CODE REVIEW

**Comment by andela-cnnadi** [comment]
Tests are not passing.

**Comment by andela-cnnadi** [comment]
What is happening here?

**Comment by andela-osule** [comment]
Re-running the build on Circle CI

**Comment by andela-cnnadi** [comment]
What's up with this PR?

**Comment by andela-osule** [comment]
Some fixes are still being applied on the branch. Also this PR needs conflicts resolved.

**Pull request merged**
